# Generated by Django 6.0.3 on 2026-05-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_appointment_reminders', models.BooleanField(default=True)),
                ('email_payment_notifications', models.BooleanField(default=True)),
                ('email_promotional', models.BooleanField(default=False)),
                ('email_system_alerts', models.BooleanField(default=True)),
                ('sms_appointment_reminders', models.BooleanField(default=False)),
                ('sms_payment_notifications', models.BooleanField(default=False)),
                ('push_appointment_reminders', models.BooleanField(default=True)),
                ('push_waitlist_updates', models.BooleanField(default=True)),
                ('push_ai_suggestions', models.BooleanField(default=True)),
                ('in_app_all', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, default='22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, default='08:00', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmation', 'Appointment Confirmation'), ('appointment_cancellation', 'Appointment Cancellation'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('payment_reminder', 'Payment Reminder'), ('payment_confirmation', 'Payment Confirmation'), ('invoice_ready', 'Invoice Ready'), ('waitlist_notification', 'Waitlist Notification'), ('ai_suggestion', 'AI Suggestion'), ('promotional', 'Promotional'), ('system_alert', 'System Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App')], default='in_app', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appointment')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.invoice')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx'), models.Index(fields=['user', 'created_at'], name='users_notif_user_id_2c9cd4_idx'), models.Index(fields=['notification_type', 'created_at'], name='users_notif_notific_5f4a5e_idx'), models.Index(fields=['is_sent', 'created_at'], name='users_notif_is_sent_613987_idx'), models.Index(fields=['expires_at'], name='users_notif_expires_f9a864_idx')],
            },
        ),
    ]
